Capabilities:
  Channel: &ChannelCapabilities
    V1_4_3: true
    V1_3: false
    V1_1: false
  Orderer: &OrdererCapabilities
    V1_4_2: true
    V1_1: true
  Application: &ApplicationCapabilities
    V1_4_2: true
    V1_3: false
    V1_2: false
    V1_1: false
  
Organizations:
 - &OrdererOrg0
     Name: OrdererOrg0MSP
     ID: OrdererOrg0MSP
     MSPDir: crypto-config/ordererOrganizations/ordererorg0/msp
     Policies: &OrdererorgPolicies
       Readers:
         Type: Signature
         Rule: “OR(‘OrdererOrg0MSP.member’)”
       Writers:
         Type: Signature
         Rule: “OR(‘OrdererOrg0MSP.member’)”
       Admins:
         Type: Signature
         Rule: “OR(‘OrdererOrg0MSP.admin’)”
 - &Org0
     Name: Org0MSP
     ID: Org0MSP

     MSPDir: crypto-config/peerOrganizations/org0/msp
     AnchorPeers:
         - Host: 10.0.1.XX (Peer 주소)
           Port: 7051
     Policies: &Org0Policies
      Readers:
         Type: Signature
         Rule: “OR(‘Org0MSP.member’)”
      Writers:
         Type: Signature
         Rule: “OR(‘Org0MSP.member’)”
      Admins:
         Type: Signature
         Rule: “OR(‘Org0MSP.admin’)”

Orderer: &OrdererDefaults
    OrdererType: kafka
    Addresses:
        - 10.0.1.XX:7050 (Orderer 주소)
    Policies:
      Readers:
         Type: ImplicitMeta
         Rule: “ANY Readers”
      Writers:
         Type: ImplicitMeta
         Rule: “ANY Writers”
      Admins:
         Type: ImplicitMeta
         Rule: “MAJORITY Admins”
      BlockValidation:
         Type: ImplicitMeta
         Rule: “ANY Writers”
    BatchTimeout: 1s

    BatchSize:
       MaxMessageCount: 30       
       AbsoluteMaxBytes: 99 MB       
       PreferredMaxBytes: 512 KB
    Kafka:
       Brokers:
        - 10.0.1.XX:9092 (Kafka 주소)
    Capabilities:
       <<: *OrdererCapabilities
    Organizations:

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: “ANY Readers”
    Writers:
      Type: ImplicitMeta
      Rule: “ANY Writers”
    Admins:
      Type: ImplicitMeta
      Rule: “MAJORITY Admins”
  Capabilities:
    <<: *ChannelCapabilities

Application: &ApplicationDefaults
 Policies:
   Readers:
     Type: ImplicitMeta
     Rule: “ANY Readers”
   Writers:
     Type: ImplicitMeta
     Rule: “ANY Writers”

   Admins:
     Type: ImplicitMeta
     Rule: “MAJORITY Admins”
 Organizations:

Profiles:

  TwoOrgsOrdererGenesis:
   Capabilities:
     <<: *ChannelCapabilities
   <<: *ChannelDefaults
   Orderer:
     <<: *OrdererDefaults
     Organizations:
       - *OrdererOrg0
   Consortiums:
     SampleConsortium:
        Organizations:
            - *Org0

  TwoOrgsChannel:
   Capabilities:
      <<: *ChannelCapabilities
   <<: *ChannelDefaults
   Consortium: SampleConsortium
   Application:
      <<: *ApplicationDefaults
      Organizations:
          - *Org0
      Capabilities:
         <<: *ApplicationCapabilities

