version: '2'
services:
   zookeeper:
     image: hyperledger/fabric-zookeeper:latest
     ports:
       - "2181:2181"

   kafka0:
    image: hyperledger/fabric-kafka:latest
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=10.0.1.62
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=0
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10380924
      - KAFKA_UNCLEAN_LEADER_ELECTION=false
      - KAFKA_UNM_REPLICA_FETCHERS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
